# DS 15. Conv2D 이해 및 사용법

> "작성완료"

- toc:true
- branch: master
- badges: true
- comments: true

# Data Science
- lenture: Data Science_11-2nd week of lectures.
- lenture date: 2022-05-16
- lecturer: Guebin choi
- study date: 2022-05-18
- author: Kione kim

In [2]:
import tensorflow as tf 
import tensorflow.experimental.numpy as tnp

In [3]:
import numpy as np

In [4]:
tf.experimental.numpy.experimental_enable_numpy_behavior()

## Conv2D

`-` Conv선언

In [5]:
conv2d = tf.keras.layers.Conv2D(1,(2,2)) # filters와 kernel_size는 디폴트값으로 선언이 되지 않기 때문에 직접 입력해주어야 함!

`-` 입력 데이터

In [20]:
XXX = tnp.arange(1*4*4*1, dtype=tf.float64) # float으로 설정!!!
XXX

<tf.Tensor: shape=(16,), dtype=float64, numpy=
array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])>

In [21]:
XXX = tnp.arange(1*4*4*1, dtype=tf.float64).reshape(1,4,4,1) # float으로 설정해주어야 함!!!
XXX

<tf.Tensor: shape=(1, 4, 4, 1), dtype=float64, numpy=
array([[[[ 0.],
         [ 1.],
         [ 2.],
         [ 3.]],

        [[ 4.],
         [ 5.],
         [ 6.],
         [ 7.]],

        [[ 8.],
         [ 9.],
         [10.],
         [11.]],

        [[12.],
         [13.],
         [14.],
         [15.]]]])>

In [22]:
conv2d(XXX)

<tf.Tensor: shape=(1, 3, 3, 1), dtype=float32, numpy=
array([[[[ 0.87437177],
         [ 0.05317581],
         [-0.76802087]],

        [[-2.4104128 ],
         [-3.2316093 ],
         [-4.0528054 ]],

        [[-5.6951976 ],
         [-6.5163946 ],
         [-7.33759   ]]]], dtype=float32)>

### 오류
: shape과 dimension을 잘 맞춰서 입력해주어야 함!

`-` 오류1: layer 선언할 때 filters와 kernel_size를 직접 입력하지 않을 경우

In [15]:
tf.keras.layers.Conv2D()

TypeError: __init__() missing 2 required positional arguments: 'filters' and 'kernel_size'

`-` 오류2: 입력데이터를 선언할 때 dimension을 (1,4,4,1)과 같이 4-dimension으로 맞춰주어야 함

In [26]:
XXX = tnp.arange(1*4*4*1).reshape(1,4,4)
XXX

<tf.Tensor: shape=(1, 4, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]])>

In [27]:
conv2d(XXX)

ValueError: Input 0 of layer "conv2d_3" is incompatible with the layer: expected min_ndim=4, found ndim=3. Full shape received: (1, 4, 4)

`-` 오류3: 입력데이터 선언할 때 dtype를 float로 설정하지 않을 경우

Conv2D layer에 입력되지 않아 수행 X! (Dense layer에서는 int형으로 입력해도 잘 수행되었음)

In [23]:
XXX = tnp.arange(1*4*4*1).reshape(1,4,4,1)
XXX

<tf.Tensor: shape=(1, 4, 4, 1), dtype=int32, numpy=
array([[[[ 0],
         [ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6],
         [ 7]],

        [[ 8],
         [ 9],
         [10],
         [11]],

        [[12],
         [13],
         [14],
         [15]]]])>

In [24]:
conv2d(XXX)

InvalidArgumentError: Exception encountered when calling layer "conv2d_3" (type Conv2D).

cannot compute Conv2D as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:Conv2D]

Call arguments received:
  • inputs=tf.Tensor(shape=(1, 4, 4, 1), dtype=int32)

- int형은 conv2d layer에 들어갈 수 없음..!!
- float이기만 하면 됨! float64가 아닌 float32, float16도 가능

### Test1
:XXX가 conv2d(XXX)로 가는 규칙을 알아보자!

In [30]:
XXX= tnp.arange(1*4*4*1,dtype=tf.float64).reshape(1,4,4,1)
XXX

<tf.Tensor: shape=(1, 4, 4, 1), dtype=float64, numpy=
array([[[[ 0.],
         [ 1.],
         [ 2.],
         [ 3.]],

        [[ 4.],
         [ 5.],
         [ 6.],
         [ 7.]],

        [[ 8.],
         [ 9.],
         [10.],
         [11.]],

        [[12.],
         [13.],
         [14.],
         [15.]]]])>

`-` 보기 좋게 표현

In [31]:
XXX.reshape(1,4,4)

<tf.Tensor: shape=(1, 4, 4), dtype=float64, numpy=
array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])>

`-` layer에 입력

In [32]:
conv2d(XXX)

<tf.Tensor: shape=(1, 3, 3, 1), dtype=float32, numpy=
array([[[[ 0.87437177],
         [ 0.05317581],
         [-0.76802087]],

        [[-2.4104128 ],
         [-3.2316093 ],
         [-4.0528054 ]],

        [[-5.6951976 ],
         [-6.5163946 ],
         [-7.33759   ]]]], dtype=float32)>

`-` 보기 좋게 표현

In [35]:
conv2d(XXX).reshape(1,3,3)

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[ 0.87437177,  0.05317581, -0.76802087],
        [-2.4104128 , -3.2316093 , -4.0528054 ],
        [-5.6951976 , -6.5163946 , -7.33759   ]]], dtype=float32)>

#### conv2d의 weight

`-` conv2d 다시 선언

In [37]:
XXX = tnp.arange(1*4*4*1,dtype=tf.float64).reshape(1,4,4,1)
conv2d = tf.keras.layers.Conv2D(1,(2,2))

In [38]:
print(XXX.reshape(1,4,4))
print(conv2d(XXX).reshape(1,3,3))

tf.Tensor(
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]
  [12. 13. 14. 15.]]], shape=(1, 4, 4), dtype=float64)
tf.Tensor(
[[[ 1.156961    0.99860877  0.84025645]
  [ 0.5235517   0.36519933  0.20684743]
  [-0.10985804 -0.26820993 -0.4265623 ]]], shape=(1, 3, 3), dtype=float32)


- 위의 값과 다름..?! 이는 Conv2d의 weight값이 conv2d를 선언해줄 때마다 달라지기 때문임!

`-` seed 고정

In [43]:
tf.random.set_seed(43052)
XXX = tnp.arange(1*4*4*1,dtype=tf.float64).reshape(1,4,4,1)
conv2d = tf.keras.layers.Conv2D(1,(2,2))

In [44]:
print(XXX.reshape(1,4,4))
print(conv2d(XXX).reshape(1,3,3))

tf.Tensor(
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]
  [12. 13. 14. 15.]]], shape=(1, 4, 4), dtype=float64)
tf.Tensor(
[[[ -4.125754   -5.312817   -6.4998803]
  [ -8.874006  -10.0610695 -11.248133 ]
  [-13.62226   -14.809322  -15.996386 ]]], shape=(1, 3, 3), dtype=float32)


- random seed를 고정하면 값이 바뀌지 않음!

`-` weight를 찍어보자

In [45]:
conv2d.weights

[<tf.Variable 'conv2d_7/kernel:0' shape=(2, 2, 1, 1) dtype=float32, numpy=
 array([[[[-0.13014299]],
 
         [[-0.23927206]]],
 
 
        [[[-0.20175874]],
 
         [[-0.6158894 ]]]], dtype=float32)>,
 <tf.Variable 'conv2d_7/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

- weight가 입력되어 있다.

In [46]:
type(conv2d.weights)

list

In [47]:
conv2d.weights[0], conv2d.weights[1]

(<tf.Variable 'conv2d_7/kernel:0' shape=(2, 2, 1, 1) dtype=float32, numpy=
 array([[[[-0.13014299]],
 
         [[-0.23927206]]],
 
 
        [[[-0.20175874]],
 
         [[-0.6158894 ]]]], dtype=float32)>,
 <tf.Variable 'conv2d_7/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>)

- 잘 살펴보니 conv2d의 weight는 리스트로 두 개의 원소로 이루어져있음
- conv2d.weight_0은 weight이고 weight_1은 bias임!

`-` weight 뜯어보기

In [52]:
tf.reshape(conv2d.weights[0],(2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.13014299, -0.23927206],
       [-0.20175874, -0.6158894 ]], dtype=float32)>

In [54]:
print(XXX.reshape(1,4,4))

tf.Tensor(
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]
  [12. 13. 14. 15.]]], shape=(1, 4, 4), dtype=float64)


In [55]:
0 * -0.13014299 + 1 * -0.23927206 + 4 * -0.20175874 + 5 * -0.6158894

-4.1257540200000005

- 이 값이 conv2d의 weight의 (1,1)값임!
- weight의 다른 원소도 마찬가지!
- 결과 관찰을 편리하게 하기 위해 weight를 직접 조정해서 확인해보자

`-` weight을 모두 0.25로, bias를 3으로 조정

In [58]:
conv2d.get_weights()

[array([[[[-0.13014299]],
 
         [[-0.23927206]]],
 
 
        [[[-0.20175874]],
 
         [[-0.6158894 ]]]], dtype=float32),
 array([0.], dtype=float32)]

`-` weight 선언

In [60]:
conv2d.get_weights()[0].shape

(2, 2, 1, 1)

In [6]:
w_ = np.array([1/4,1/4,1/4,1/4],dtype=np.float32).reshape(2,2,1,1) # 혹시 모르니 np.flate32로 설정!! tf.float32 아님!

`-` bias 선언

In [67]:
conv2d.get_weights()[1].shape

(1,)

In [70]:
b_ = np.array([3],dtype=np.float32)

In [72]:
conv2d.set_weights([w_,b_])

In [74]:
conv2d.get_weights()

[array([[[[0.25]],
 
         [[0.25]]],
 
 
        [[[0.25]],
 
         [[0.25]]]], dtype=float32),
 array([3.], dtype=float32)]

- 변경 완료...!

In [75]:
print(XXX.reshape(1,4,4))
print(conv2d(XXX).reshape(1,3,3))

tf.Tensor(
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]
  [12. 13. 14. 15.]]], shape=(1, 4, 4), dtype=float64)
tf.Tensor(
[[[ 5.5  6.5  7.5]
  [ 9.5 10.5 11.5]
  [13.5 14.5 15.5]]], shape=(1, 3, 3), dtype=float32)


In [76]:
(0+1+4+5)/4 +3, (1+2+5+6)/4 +3, (2+3+6+7)/4 +3 

(5.5, 6.5, 7.5)

- 앞서 conv2d layer를 선언할 때 (2,2)를 입력했는데, 이는 결국 (2,2)의 각 원소에 weight를 각각 곱해줘서 합한 후 bias를 더해준 것으로 이해할 수 있음

#### tf.keras.layers.Conv2D(1,kernel_size=(2,2)) 요약

``` python
1. size=(2,2)인 윈도우를 만든다.
2. XXX에 윈도우를 통과시켜 (2,2)크기의 sub XXX 를 얻는다. sub XXX의 각 원소에 conv2d.weights_0의 각 원소를 element-wise하게 곱한다. 
3. 2의 결과를 모두 더한 결과에 다시 conv2d.weights_1을 수행한다.
4. 윈도우를 이동시키면서 반복한다!
```

### Test2
: 여러개의 관측치

`-` 관측치가 여러개일 경우

`-` 입력 데이터

In [79]:
XXX = tnp.arange(2*4*4*1,dtype=tf.float64).reshape(2,4,4,1)
XXX.reshape(2,4,4)

<tf.Tensor: shape=(2, 4, 4), dtype=float64, numpy=
array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]],

       [[16., 17., 18., 19.],
        [20., 21., 22., 23.],
        [24., 25., 26., 27.],
        [28., 29., 30., 31.]]])>

`-` conv2d의 weight

In [82]:
conv2d.weights

[<tf.Variable 'conv2d_7/kernel:0' shape=(2, 2, 1, 1) dtype=float32, numpy=
 array([[[[0.25]],
 
         [[0.25]]],
 
 
        [[[0.25]],
 
         [[0.25]]]], dtype=float32)>,
 <tf.Variable 'conv2d_7/bias:0' shape=(1,) dtype=float32, numpy=array([3.], dtype=float32)>]

In [84]:
conv2d(XXX).reshape(2,3,3)

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[ 5.5,  6.5,  7.5],
        [ 9.5, 10.5, 11.5],
        [13.5, 14.5, 15.5]],

       [[21.5, 22.5, 23.5],
        [25.5, 26.5, 27.5],
        [29.5, 30.5, 31.5]]], dtype=float32)>

In [86]:
(16+17+20+21)/4 + 3 , (17+18+21+22)/4 + 3 

(21.5, 22.5)

- 관측치 별로 수행해주었음!

### Test3
: 윈도우 크기가 (3,3)

`-` 윈도우 크기를 바꿔보자

`-` 입력데이터

In [94]:
XXX = tnp.array([1]*1*4*4*1,dtype=tf.float64).reshape(1,4,4,1)
XXX.reshape(1,4,4)

<tf.Tensor: shape=(1, 4, 4), dtype=float64, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])>

- 위와 같이 선언하면 conv2d 수행결과 weight의 합으로 나오기 때문에 확인이 쉬움!

`-` 윈도우 크기를 바꿔 layer 선언

In [96]:
conv2d = tf.keras.layers.Conv2D(1,(3,3))
conv2d(XXX)

<tf.Tensor: shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[0.4258361],
         [0.4258361]],

        [[0.4258361],
         [0.4258361]]]], dtype=float32)>

In [97]:
conv2d(XXX).reshape(1,2,2)

<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[0.4258361, 0.4258361],
        [0.4258361, 0.4258361]]], dtype=float32)>

- conv2d 수행결과 위와 같이 나왔음

In [104]:
conv2d.weights[0]

<tf.Variable 'conv2d_9/kernel:0' shape=(3, 3, 1, 1) dtype=float32, numpy=
array([[[[-0.3444655 ]],

        [[ 0.4521824 ]],

        [[ 0.236296  ]]],


       [[[ 0.54707503]],

        [[ 0.19746327]],

        [[ 0.20471048]]],


       [[[-0.1245549 ]],

        [[-0.25237298]],

        [[-0.4904977 ]]]], dtype=float32)>

In [102]:
tf.reshape(conv2d.weights[0],(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.3444655 ,  0.4521824 ,  0.236296  ],
       [ 0.54707503,  0.19746327,  0.20471048],
       [-0.1245549 , -0.25237298, -0.4904977 ]], dtype=float32)>

- kernel_size가 (3,3)인 conv2d의 weight는 총 9개가 나왔음!

In [105]:
tf.reduce_sum(tf.reshape(conv2d.weights[0],(3,3)))

<tf.Tensor: shape=(), dtype=float32, numpy=0.4258361>

- 위의 값과 동일하게 나왔다!

### Test4

`-` 입력데이터

In [200]:
XXX = tf.constant([[3,3,2,1,0],[0,0,1,3,1],[3,1,2,2,3],[2,0,0,2,2],[2,0,0,0,1]],dtype=tf.float64).reshape(1,5,5,1)
XXX

<tf.Tensor: shape=(1, 5, 5, 1), dtype=float64, numpy=
array([[[[3.],
         [3.],
         [2.],
         [1.],
         [0.]],

        [[0.],
         [0.],
         [1.],
         [3.],
         [1.]],

        [[3.],
         [1.],
         [2.],
         [2.],
         [3.]],

        [[2.],
         [0.],
         [0.],
         [2.],
         [2.]],

        [[2.],
         [0.],
         [0.],
         [0.],
         [1.]]]])>

`-` layer

In [201]:
conv2d = tf.keras.layers.Conv2D(1,(3,3))

In [202]:
conv2d.get_weights()

[]

- 아무값도 나오지 않았는데, 한 번 수행해주면 나온다

In [203]:
conv2d(XXX)

<tf.Tensor: shape=(1, 3, 3, 1), dtype=float32, numpy=
array([[[[-1.4967487 ],
         [-1.4661053 ],
         [ 0.36124906]],

        [[-1.1427999 ],
         [ 0.5735489 ],
         [-1.8295492 ]],

        [[-1.3771133 ],
         [-1.2894611 ],
         [-0.09080273]]]], dtype=float32)>

In [204]:
conv2d.get_weights()

[array([[[[-0.22610146]],
 
         [[-0.47850692]],
 
         [[ 0.2982087 ]]],
 
 
        [[[-0.41198692]],
 
         [[ 0.49046123]],
 
         [[-0.35138166]]],
 
 
        [[[ 0.00362712]],
 
         [[ 0.06990165]],
 
         [[ 0.14562875]]]], dtype=float32),
 array([0.], dtype=float32)]

`-` weight 값을 위 그림대로 바꿔보자

In [205]:
conv2d.weights[0].shape

TensorShape([3, 3, 1, 1])

In [206]:
w_ = np.array([[0,1,2],[2,2,0],[0,1,2]],dtype=np.float32).reshape(3,3,1,1)
b_ = np.array([0],dtype=np.float32)

In [212]:
conv2d.set_weights([w_,b_])

In [213]:
conv2d.get_weights()

[array([[[[0.]],
 
         [[1.]],
 
         [[2.]]],
 
 
        [[[2.]],
 
         [[2.]],
 
         [[0.]]],
 
 
        [[[0.]],
 
         [[1.]],
 
         [[2.]]]], dtype=float32),
 array([0.], dtype=float32)]

`-` 수행

In [214]:
conv2d(XXX).reshape(1,3,3)

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[12., 12., 17.],
        [10., 17., 19.],
        [ 9.,  6., 14.]]], dtype=float32)>

- 같은 결과가 나왔음

### Test5
: conv2d의 채널이 여러개일 경우

이해하는데 초점!

`-` 입력데이터: 구조를 쉽게 파악하기 위해 이미지 차원을 2X2로 입력!

In [128]:
XXX= tnp.array([1]*1*2*2*1,dtype=np.float64).reshape(1,2,2,1)
XXX.reshape(1,2,2)

<tf.Tensor: shape=(1, 2, 2), dtype=float64, numpy=
array([[[1., 1.],
        [1., 1.]]])>

`-` conv2d layer

In [130]:
conv2d = tf.keras.layers.Conv2D(4,(2,2))

In [131]:
conv2d(XXX)

<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=
array([[[[-1.4677291 ,  0.4884689 ,  0.74202406, -0.2235254 ]]]],
      dtype=float32)>

- 채널이 4개라서 4개의 값이 나왔음

In [132]:
conv2d.weights[0]

<tf.Variable 'conv2d_11/kernel:0' shape=(2, 2, 1, 4) dtype=float32, numpy=
array([[[[-0.40807962,  0.52427983,  0.02677613,  0.32642812]],

        [[-0.37817764, -0.16062203, -0.18941301,  0.1360228 ]]],


       [[[-0.26373935,  0.2107814 ,  0.42705786, -0.379741  ]],

        [[-0.41773254, -0.08597028,  0.47760308, -0.3062353 ]]]],
      dtype=float32)>

In [133]:
np.array(conv2d.weights[0])[...,0]

array([[[-0.40807962],
        [-0.37817764]],

       [[-0.26373935],
        [-0.41773254]]], dtype=float32)

In [138]:
print(np.array(conv2d.weights[0])[...,0].sum()) # conv2d(XXX)의 첫 번째 채널
print(np.array(conv2d.weights[0])[...,1].sum()) # conv2d(XXX)의 두 번째 채널
print(np.array(conv2d.weights[0])[...,2].sum()) # conv2d(XXX)의 세 번째 채널
print(np.array(conv2d.weights[0])[...,3].sum()) # conv2d(XXX)의 네 번째 채널

-1.4677291
0.4884689
0.74202406
-0.2235254


- 이는 conv2d(XXX)해서 나온 값과 같음
- 즉 이를 해석해보면, XXX의 각 원소와 conv2d의 weight가 곱한 후 더해진 것, 마지막에 bias까지 더해짐!
- XXX의 각 원소와 np.array(conv2d.weights_0)(...,0)의 곱이 더해진 것 + bias
- XXX의 각 원소와 np.array(conv2d.weights_1)(...,0)의 곱이 더해진 것 + bias
- XXX의 각 원소와 np.array(conv2d.weights_2)(...,0)의 곱이 더해진 것 + bias
- XXX의 각 원소와 np.array(conv2d.weights_3)(...,0)의 곱이 더해진 것 + bias

In [139]:
XXX.shape

TensorShape([1, 2, 2, 1])

In [140]:
conv2d(XXX).shape

TensorShape([1, 1, 1, 4])

- conv2d : (2,2,1)를 (1,1,4)로 바꾸는 변환

### Test6
: X의 채널도 여러개이고, conv2d의 채널도 여러개인 경우

`-` X의 채널(여러개)

In [141]:
XXX = tnp.array([1]*1*2*2*3, dtype=tf.float64).reshape(1,2,2,3)

`-` conv2d의 채널(여러개)

In [143]:
conv2d = tf.keras.layers.Conv2D(4,(2,2))

In [144]:
conv2d(XXX)

<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=
array([[[[-0.54339075,  1.3631663 , -0.9375297 , -0.8216876 ]]]],
      dtype=float32)>

In [146]:
XXX.shape

TensorShape([1, 2, 2, 3])

In [148]:
conv2d(XXX).shape

TensorShape([1, 1, 1, 4])

- conv2d: (2,2,3)를 (1,1,4)로 바꾸는 변환

In [149]:
conv2d.weights

[<tf.Variable 'conv2d_12/kernel:0' shape=(2, 2, 3, 4) dtype=float32, numpy=
 array([[[[ 0.14296657,  0.29063046, -0.16084617, -0.38816312],
          [-0.26042533,  0.04160446, -0.00092056,  0.14737642],
          [ 0.04154938,  0.03081837,  0.27620882,  0.2885393 ]],
 
         [[-0.38504142,  0.33944142, -0.24234334, -0.44853008],
          [-0.31522053, -0.02353916, -0.4453768 ,  0.1877119 ],
          [ 0.4252556 , -0.16301763,  0.12105966, -0.30270743]]],
 
 
        [[[ 0.10244733,  0.33534002, -0.37038288,  0.05224985],
          [ 0.2591073 , -0.26695603, -0.00175968, -0.08472571],
          [-0.43148908,  0.24909633,  0.02140689, -0.27608246]],
 
         [[-0.23761038, -0.10803497, -0.18119308, -0.20244324],
          [ 0.15658379,  0.4092812 ,  0.19860888,  0.45083874],
          [-0.04151398,  0.22850174, -0.15199137, -0.24575166]]]],
       dtype=float32)>,
 <tf.Variable 'conv2d_12/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]

- 처음 (2,2)는 kernel_size(window size) // 3은 XXX의 채널수 // 4는 conv(XXX)의 채널수

In [150]:
conv2d(XXX)

<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=
array([[[[-0.54339075,  1.3631663 , -0.9375297 , -0.8216876 ]]]],
      dtype=float32)>

In [161]:
print(np.array(conv2d.weights[0])[...,0].sum()) # conv(XXX)의 첫 번째채널
print(np.array(conv2d.weights[0])[...,1].sum()) # conv(XXX)의 두번째채널
print(np.array(conv2d.weights[0])[...,2].sum()) # conv(XXX)의 세번째채널
print(np.array(conv2d.weights[0])[...,3].sum()) # conv(XXX)의 네번째채널

-0.54339075
1.3631663
-0.9375297
-0.8216876


- 이 값은 위의 XXX에 conv2d를 수행해준 값이다

In [164]:
np.array(conv2d.weights[0])[...,0]

array([[[ 0.14296657, -0.26042533,  0.04154938],
        [-0.38504142, -0.31522053,  0.4252556 ]],

       [[ 0.10244733,  0.2591073 , -0.43148908],
        [-0.23761038,  0.15658379, -0.04151398]]], dtype=float32)

In [165]:
np.array(conv2d.weights[0])[...,0].shape

(2, 2, 3)

In [175]:
conv2d(XXX)

<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=
array([[[[-0.54339075,  1.3631663 , -0.9375297 , -0.8216876 ]]]],
      dtype=float32)>

In [168]:
W_red = np.array(conv2d.weights[0])[...,0][...,0]
W_green = np.array(conv2d.weights[0])[...,0][...,1]
W_blue = np.array(conv2d.weights[0])[...,0][...,2]

In [171]:
(W_blue+ W_green+W_red).sum()

-0.54339075

- 이는 conv(XXX)의 첫 채널 결과와 같다

In [172]:
W_red = np.array(conv2d.weights[0])[...,1][...,0]
W_green = np.array(conv2d.weights[0])[...,1][...,1]
W_blue = np.array(conv2d.weights[0])[...,1][...,2]
(W_blue+ W_green+W_red).sum()

1.3631662

- conv(XXX)의 두번째 채널 결과

In [173]:
W_red = np.array(conv2d.weights[0])[...,2][...,0]
W_green = np.array(conv2d.weights[0])[...,2][...,1]
W_blue = np.array(conv2d.weights[0])[...,2][...,2]
(W_blue+ W_green+W_red).sum()

-0.9375297

- conv(XXX)의 세번째 채널 결과

In [174]:
W_red = np.array(conv2d.weights[0])[...,3][...,0]
W_green = np.array(conv2d.weights[0])[...,3][...,1]
W_blue = np.array(conv2d.weights[0])[...,3][...,2]
(W_blue+ W_green+W_red).sum()

-0.8216876

- conv(XXX)의 네번째 채널 결과

#### 추가학습

아래와 같은 흑백이미지가 있다고 하자. 
``` python
0 0 0 1 1 1 
0 0 0 1 1 1 
0 0 0 1 1 1 
0 0 0 1 1 1 
0 0 0 1 1 1
0 0 0 1 1 1 
```

위의 이미지에 아래와 같은 weight를 가진 필터를 적용하여 convolution한 결과를 계산하라. (bias는 0으로 가정한다) 
``` python
-1 1 
-1 1 
```

In [240]:
XXX = tf.constant([[0,0,0,1,1,1],[0,0,0,1,1,1],[0,0,0,1,1,1],[0,0,0,1,1,1],[0,0,0,1,1,1],[0,0,0,1,1,1]],dtype=tf.float64).reshape(1,6,6,1)
XXX.reshape(1,6,6)

<tf.Tensor: shape=(1, 6, 6), dtype=float64, numpy=
array([[[0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.]]])>

In [241]:
conv = tf.keras.layers.Conv2D(1,(2,2))

In [242]:
conv(XXX)
conv.get_weights()[0]

array([[[[ 0.32510954]],

        [[-0.38077185]]],


       [[[ 0.06901664]],

        [[ 0.00975025]]]], dtype=float32)

In [243]:
conv.get_weights()[0].shape

(2, 2, 1, 1)

In [244]:
w_ = np.array([[-1, 1], [-1, 1]], dtype=np.float32).reshape(2,2,1,1)
b_ = np.array([0], dtype=np.float32)

In [245]:
conv.set_weights([w_,b_])

In [246]:
conv.get_weights()

[array([[[[-1.]],
 
         [[ 1.]]],
 
 
        [[[-1.]],
 
         [[ 1.]]]], dtype=float32),
 array([0.], dtype=float32)]

In [247]:
conv(XXX)

<tf.Tensor: shape=(1, 5, 5, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [2.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [2.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [2.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [2.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [2.],
         [0.],
         [0.]]]], dtype=float32)>

In [248]:
conv(XXX).reshape(1,5,5)

<tf.Tensor: shape=(1, 5, 5), dtype=float32, numpy=
array([[[0., 0., 2., 0., 0.],
        [0., 0., 2., 0., 0.],
        [0., 0., 2., 0., 0.],
        [0., 0., 2., 0., 0.],
        [0., 0., 2., 0., 0.]]], dtype=float32)>

- 계산결과 위의 값이 나왔다. 