# DS 2. Tensorflow 기본 문법(2), tf.GradientTape()

> "작성완료"

- toc:true
- branch: master
- badges: true
- comments: true
- [python, Data Science]

---
# Data Science
- lenture: Data Science_3-2nd week of lectures.
- lenture date: 2022-03-21
- lecturer: Guebin choi
- study date: 2022-03-22
- author: Kione kim
---

In [1]:
import tensorflow as tf
import numpy as np

### tnp

#### tnp 사용배경

`-` tf.constant는 쓰기 너무 어려움! 넘파이가 지원하는 편리한 기능을 사용할 수 없음

어려운 점 1: .reshape() 메소드 불가능/ tf.reshape()만 가능

어려운 점 2: .transpose(), .T 불가능/ tf.transpose()만 가능

어려운 점 3: 암묵적 형변환 불가능

어려운 점 4: (2,2) @ (2,) 연산 불가능

등등

`-` 예시1: .reshape()

In [2]:
a=np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [3]:
a=tf.constant([1,2,3,4]).reshape(2,2)

AttributeError: 
        'EagerTensor' object has no attribute 'reshape'.
        If you are looking for numpy-related methods, please run the following:
        from tensorflow.python.ops.numpy_ops import np_config
        np_config.enable_numpy_behavior()

In [ ]:
tf.reshape(tf.constant([1,2,3,4]),(2,2)) # 이렇게 써야함

`-` 예시2: .transpose()

In [4]:
np.array([1,2,3,4]).transpose().reshape(2,2).T

array([[1, 3],
       [2, 4]])

In [5]:
tf.constant([1,2,3,4]).transpose()

AttributeError: 
        'EagerTensor' object has no attribute 'transpose'.
        If you are looking for numpy-related methods, please run the following:
        from tensorflow.python.ops.numpy_ops import np_config
        np_config.enable_numpy_behavior()

In [6]:
tf.transpose(tf.constant([1,2,3,4])) # 이렇게 써야함

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [7]:
tf.transpose(tf.reshape(tf.transpose(tf.constant([1,2,3,4])),(2,2)))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]])>

- 쓰기 불편,,

`-` 예시3: 암묵적 형변환

In [8]:
np.array([1,2,3])+np.array([1.1,2.2,3.3])

array([2.1, 4.2, 6.3])

In [9]:
tf.constant([1,2,3])+tf.constant([1.1,2.2,3.3])

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2]

- 암묵적 형변환 안 됨,,

`-` 예시4: .max, .min 등등
넘파이에서 가능한 .max를 사용하려면 tf.constant에서는 tf.reduce_max()를 .min를 사용하려면 tf.reduce_min()를 사용해야함

In [10]:
tf.reduce_max(tf.transpose(tf.reshape(tf.transpose(tf.constant([1,2,3,4])),(2,2))))

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [11]:
tf.reduce_min(tf.transpose(tf.reshape(tf.transpose(tf.constant([1,2,3,4])),(2,2))))

<tf.Tensor: shape=(), dtype=int32, numpy=1>

`-` 예시5: (2,2) @ (2,) 연산

In [12]:
np.array([[1.0,2.0],[3.0,4.0]]) @ np.array([1,2])

array([ 5., 11.])

In [13]:
np.array([1,2]) @ np.array([[1.0,2.0],[3.0,4.0]])

array([ 7., 10.])

- 차원이 맞지 않아도 넘파이에서는 알아서 잘 계산해줌

In [14]:
np.array([[1.0,2.0],[3.0,4.0]]) @ np.array([1,2]).reshape(2,1)

array([[ 5.],
       [11.]])

In [15]:
np.array([1,2]).reshape(2,1) @ np.array([[1.0,2.0],[3.0,4.0]])

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

- 헷갈릴 것 같다면 .reshape()를 써서 명시해줄 수 있다

In [16]:
tf.constant([[1.0,2.0],[3.0,4.0]]) @ tf.constant([1,2])

InvalidArgumentError: cannot compute MatMul as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:MatMul]

- 차원이 맞지 않으면 계산을 하지 않는다.

#### tnp 사용

In [17]:
import tensorflow.experimental.numpy as tnp   # tnp를 사용하면 넘파이에 익숙한 문법을 모두 쓸 수 있음
tnp.experimental_enable_numpy_behavior()   # 기존에 생성된 tf.constant 자료형은 넘파이와 유사하게 동작한다. 

In [18]:
tnp.array([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [19]:
tnp.diag([1,1])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 1]])>

#### 타입

In [20]:
type(tf.constant([1,2])),type(tnp.array([1,2]))

(tensorflow.python.framework.ops.EagerTensor,
 tensorflow.python.framework.ops.EagerTensor)

- tnp를 사용해도 타입은 변하지 않는다. 모두 EagerTensor

`-` 앞서 본 어려운 점 1인 .reshape()가 사용 가능!

In [21]:
tf.constant([1,2,3,4]).reshape(2,2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

`-` 어려운 점 2인 .transpose, .T 도 사용 가능!

In [22]:
tf.constant([1,2,3,4]).reshape(2,2).transpose().T

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

`-` 어려운 점 3인 암묵적 형변환도 가능!

In [23]:
tf.constant([1,2,3]) + tf.constant([1.1,2.2,3.3])

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2.10000002, 4.20000005, 6.29999995])>

`-` 어려운 점 4인 .max(), .min() 등도 가능!

In [24]:
tf.constant([1,2,3]) +tf.constant([1.1,2.2,3.3]).max()

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([4.29999995, 5.29999995, 6.29999995])>

In [25]:
tf.constant([1,2,3]) + tf.constant([1.1,2.2,3.3]).min()

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2.10000002, 3.10000002, 4.10000002])>

`-` 어려운 점 5인 (2,2) @ (2,)의 연산도 가능!

In [26]:
tnp.diag([1,1]) @ tf.constant([1,2])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [27]:
tf.constant([1,2]) @ tnp.diag([1,1])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

- 많은 단점을 개선했음!!

`-` 하지만 안 되는 것도 있음

In [28]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [29]:
a[0] = 0
a

array([0, 2, 3])

In [30]:
a=tnp.array([1,2,3])
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [31]:
a[0]=0
a

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

- 이는 안 됨

### tf.Variable

#### 예비학습

In [32]:
a=8
a

8

In [33]:
id(a)

140715972567008

In [34]:
a=10
a

10

In [35]:
id(a)

140715972567072

- 이는 값을 변경(편집)한 것이 아니라 재할당한 것이다.

In [36]:
b=10
id(b)

140715972567072

1) tf.constant는 메모리에 그 값을 올리는 것 -> 메모리에 있는 것은 바꿀 수 없음 -> 값을 변경하고자 하면 재할당 해야 함

2) tf.Variable은 메모리에 있는 값을 변경(편집)할 수 있음

---

`-` 선언

In [37]:
tf.Variable([1,2])

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>

`-` type

In [38]:
type(tf.Variable([1,2]))

tensorflow.python.ops.resource_variable_ops.ResourceVariable

- ResourceVariable 처음 보는 타입

`-` tf.constant() 선언 후 변환

In [39]:
tf.Variable(tf.constant([1,2]))

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>

`-` np.array() 선언 후 변환

In [40]:
tf.Variable(np.array([1,2]))

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>

`-` 인덱싱

In [41]:
a=tf.Variable([1,2,3,4])
a[:2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

`-` 연산

In [42]:
tf.Variable([1,2]) + tf.Variable([2,1])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 3])>

- 그런데 살펴보니, 인덱싱과 연산 후에 자료형이 tf.Variable에서 tf.Tensor로 바꼈다.

In [43]:
a=tf.Variable([1,2])
b=tf.Variable([2,1])
type(a), type(b)

(tensorflow.python.ops.resource_variable_ops.ResourceVariable,
 tensorflow.python.ops.resource_variable_ops.ResourceVariable)

In [44]:
type(a+b)

tensorflow.python.framework.ops.EagerTensor

- tf.Variable()로 만든 후 간단한연산을 하면 그 결과는 tf.constant()로 만든 오브젝트와 동일해짐. 

In [45]:
tf.Variable([1,2]) + tf.Variable([1.1,2.2])

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([2.10000002, 4.20000005])>

- 이는 원래 안 되지만, tnp.experimental_enable_numpy_behavior()를 선언하면 가능함

In [46]:
tf.Variable([1,2,3,4]).reshape(2,2)

AttributeError: 'ResourceVariable' object has no attribute 'reshape'

- 이것은 또 안 됨..

- tnp의 전부 되는 것은 아니고 일부만 가능

`-` tf.concat

In [47]:
a=tf.Variable([[1,2],[3,4]])
b=tf.Variable([[-1,-2],[-3,-4]])

In [48]:
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 3,  4],
       [-1, -2],
       [-3, -4]])>

In [49]:
tf.concat([a,b],axis=1)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 1,  2, -1, -2],
       [ 3,  4, -3, -4]])>

`-` tf.stack

In [50]:
tf.stack([a,b],axis=0)

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[-1, -2],
        [-3, -4]]])>

In [51]:
tf.stack([a,b],axis=1)

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [-1, -2]],

       [[ 3,  4],
        [-3, -4]]])>

`-` 변수값 변경 가능

In [52]:
a=tf.Variable([1,2])
a

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>

In [53]:
id(a)

1561676107296

In [54]:
a.assign_add([-1,2])
a

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([0, 4])>

In [55]:
id(a)

1561676107296

- 위를 살펴보니, 메모리 주소가 같다. 즉 값이 재할당 된 것이 아닌 변경된 것임을 알 수 있다.

: tf.constant()는 일반메모리에, tf.Variable은 GPU에

### 미분
:Tensorflow를 사용하는 가장 큰 이유

모티브

`-` 예제: 컴퓨터를 이용하여 $x=2$에서 $y=3x^2$의 접선의 기울기를 구해보자. 

`-` (손풀이)

$\frac{dy}{dx}=6x$ 이므로, $x=2$를 대입 -> 답 : 12.

`-` (컴퓨터로 풀이) 

도함수를 어떻게 구할지 모르겠으나 일단 $x=2$에서 접선의 기울기만 계산해보자

step 1: 답만계산 

In [56]:
x1=2
y1=3*x1**2

In [57]:
x2=2.000001
y2=3*x2**2

In [58]:
(y2-y1)/(x2-x1)

12.000003000266702

step 2: 함수화

In [59]:
def f(x):
    return 3*x**2

In [60]:
def d(f,x): # python에서는 d(f,x)로 선언 가능
    return (f(x+0.000001)-f(x))/0.000001   # f(x+a)-f(x)/a 꼴

In [61]:
d(f,2)

12.000003001944037

In [62]:
d(f,3)

18.000003002782705

step 3: lambda 이용

In [63]:
d(lambda x: 3*x**2,2)

12.000003001944037

In [64]:
d(lambda x: 3*x**2,3)

18.000003002782705

In [65]:
d(lambda x: x**2,3)

6.000001000927568

`-` 2개의 변수를 가지는 함수에 대한 미분

In [66]:
def d(f,x):
    return (f(x+0.000001)-f(x))/0.000001

In [67]:
def f(x,y):
    return x**2 + 3*y

In [68]:
d(f,(3,2)) # 미분을 하는 함수 d에 x**2+3*y를 적용시켜 미분시킨 후 x,y에 3,2를 각각 대입하라.

TypeError: can only concatenate tuple (not "float") to tuple

- 오류가 남

- 이는 확장성이 떨어지기 때문에 다른 방법이 필요함

#### tf.GradientTape()

`-` 예제1: $x=2$에서 $y=3x^2$의 도함수 값을 구하여라.

In [69]:
x=tf.Variable([2.0])
a=tf.constant([3.0])

In [70]:
# tf.GradientTape?

In [71]:
tf.GradientTape()

- 무엇인가 만들어졌음

In [72]:
mytape=tf.GradientTape()

In [73]:
dir(mytape)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_ensure_recording',
 '_persistent',
 '_pop_tape',
 '_push_tape',
 '_recording',
 '_tape',
 '_tf_api_names',
 '_tf_api_names_v1',
 '_watch_accessed_variables',
 '_watched_variables',
 'batch_jacobian',
 'gradient',
 'jacobian',
 'reset',
 'stop_recording',
 'watch',
 'watched_variables']

- dir()을 찍어보니 다음과 같은 게 있음
1. `__enter__`
2. `__exit__`

In [74]:
?mytape.__enter__

Signature: mytape.__enter__()
Docstring: Enters a context inside which operations are recorded on this tape.
File:      c:\users\kko\anaconda3\envs\ds2022\lib\site-packages\tensorflow\python\eager\backprop.py
Type:      method


- 이는 함수이고 tape를 기록하는 기능을 함

In [75]:
?mytape.__exit__

Signature: mytape.__exit__(typ, value, traceback)
Docstring: Exits the recording context, no further operations are traced.
File:      c:\users\kko\anaconda3\envs\ds2022\lib\site-packages\tensorflow\python\eager\backprop.py
Type:      method


- 함수인데 ( )안에 None, None, None를 입력해주어야 한다. 기록을 끄는 기능을 함

``` python
tf.GradientTape() 사용법:
mytape.__enter__
기록할 내용
mytape.__exit__
```

In [76]:
x=tf.Variable([2.0]) # 미분하고 싶은 변수는 Variable로 할당
a=tf.constant([3.0]) # a는 상수로, 값을 저장하고 싶은 것은 constant로 할당

In [77]:
mytape.__enter__()
y=a*x**2
mytape.__exit__(None,None,None)

In [78]:
mytape.gradient(y,x) # 변수 x로 y를 미분

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([12.], dtype=float32)>

`-` 예제2

In [79]:
x=tf.Variable([2.0])

In [80]:
mytape=tf.GradientTape()

In [81]:
mytape.__enter__()
a=(x/2)*3 # a를 기록할 내용으로 가져왔음
y=a*x**2
mytape.__exit__(None,None,None)

In [82]:
mytape.gradient(y,x) # 변수 x로 y를 미분

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([18.], dtype=float32)>

- a를 기록할 내용에서 지정해준 것 뿐인데 12가 아닌 18이 나왔음

- 이는 다음의 과정을 통해 나온 결과임

$a=\frac{3}{2}x$

$y=ax^2= \frac{3}{2}x^3$

$\frac{dy}{dx}= \frac{3}{2}3 x^2$

1.5 × 3 × 4 = 18

In [83]:
1.5 * 3 * 4

18.0

- 즉 y는 $a=3$을 기록한 것이 아니라, $a=\frac{3}{2}x$를 기록한 것이다.

`-` 테이프의 개념(중요)

`-` 상황 예시

미분계산을 컴퓨터에게 부탁하고 싶다. 예를 들어 $y=3x^2$에 대한 미분계산을 컴퓨터에 부탁 하기 위해서는 노트 및 연습장(=테이프)에 $y=3x^2$이라는 수식을 써서 보여줘야 한다. 이 때 컴퓨터에게 식($y$)이 무엇인지 그리고 무엇으로 미분하고 싶은지($x$)를 명시해야 한다. 

`-` 비유

(1) `mytape = tf.GradientTape()`:  
- `tf.GradientTape()` 는 컴퓨터에게 전달할 노트 생성
- `mytape=` 는 생성한 노트의 이름을 mytape이라고 지정 

(2) `mytape.__enter__()`: 
- `mytape` 라는 노트를 연다.

(3) `a=x/2*3; y=a*x**2`: 
- 컴퓨터에게 보여줄 식(미분하고자 하는 식)

(4) `mytape.__exit__(None,None,None)`: mytape라는 공책을 닫는다. 
- `mytape` 라는 노트를 닫는다.

(5) `mytape.gradient(y,x)`: $y$를 $x$로 미분한다는 메모를 남겨 컴퓨터에 전달

`-` 여기서 가장 중요한 것은 노트를 `언제 열고 닫는지`이다

`1)`

In [87]:
#1
x=tf.Variable([2.0])
a=x/2*3 # a=x*(3/2) -> a=3
#2
mytape=tf.GradientTape()
#3
mytape.__enter__()
y=a*x**2 # y=3*x**2, a는 이미 3의 값을 가짐
mytape.__exit__(None,None,None)
#4
mytape.gradient(y,x)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([12.], dtype=float32)>

`2)`

In [89]:
#1
x=tf.Variable([2.0])
#2
mytape=tf.GradientTape()
#3
mytape.__enter__()
a=x/2*3 
y=a*x**2 # a=(3*x)/2로 y=(3*x)/2*x**2
mytape.__exit__(None,None,None)
#4
mytape.gradient(y,x)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([18.], dtype=float32)>

- 이를 유심히 살펴보니, 코드가 뭔가 깔끔하지가 않음. 중복되는 것도 있어 보임.

- 보다 깔끔하고 효율적인 코드가 필요! -> `with문`활용

`-` 참고: `x=tf.constant([2])` float형으로 입력하지 않으면 오류!! `tf.Variable([2])`도 마찬가지

In [137]:
#1
x=tf.constant([2])
#2
mytape=tf.GradientTape()
#3
mytape.__enter__()
a=x/2*3 
y=a*x**2 # a=(3*x)/2로 y=(3*x)/2*x**2
mytape.__exit__(None,None,None)
#4
mytape.gradient(y,x)

In [138]:
#1
x=tf.Variable([2])
#2
mytape=tf.GradientTape()
#3
mytape.__enter__()
a=x/2*3 
y=a*x**2 # a=(3*x)/2로 y=(3*x)/2*x**2
mytape.__exit__(None,None,None)
#4
mytape.gradient(y,x)

#### with문을 활용한 tf.GradientTape()

``` python
with문 사용법:
    with tf.GradientTape() as mytape:
        컴퓨터에게 전달할 수식
 
1. tf.GradientTape()를 실행하면 오브젝트가 하나 생성되는데 이를 mytape라고 지정한다.
    기존에 mytape=tf.GradientTape()을 with tf.GradientTape as mytape으로 지정해준다. 
2. with문이 시작되면서 mytape.__enter__()이 실행
3. 컴퓨터에게 전달한 수식 실행 
4. with문이 끝나면서 mytape.__exit__(None,None,None)가 실행 
```

`-` with문 사용한 예제 풀이

`1)`

In [98]:
x=tf.Variable([2.0])
a=x/2*3 

with tf.GradientTape() as mytape:
    y=a*x**2

mytape.gradient(y,x)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([12.], dtype=float32)>

`2)`

In [101]:
x=tf.Variable([2.0])

with tf.GradientTape() as mytape:
    a=x/2*3
    y=a*x**2
    
mytape.gradient(y,x)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([18.], dtype=float32)>

`-` `persistent=True:` 계산한 값을 버리지 않는 기능으로 계속해서 출력할 수 있다

In [114]:
x=tf.Variable([2.0])
a=x/2*3

with tf.GradientTape() as mytape:
    y=a*x**2

In [115]:
mytape.gradient(y,x),mytape.gradient(y,x)

RuntimeError: A non-persistent GradientTape can only be used to compute one set of gradients (or jacobians)

- 두 번 실행하면 오류가 난다

In [118]:
x=tf.Variable([2.0])
a=x/2*3

with tf.GradientTape(persistent=True) as mytape:
    y=a*x**2

In [119]:
mytape.gradient(y,x),mytape.gradient(y,x)

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([12.], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([12.], dtype=float32)>)

- 오류 해결!

`-` 미분계산에 사용할 변수($x$)를 tf.constant로 설정하면 계산이 되지 않는다.

In [121]:
x=tf.constant([2.0])
a=x/2*3

with tf.GradientTape(persistent=True) as mytape:
    y=a*x**2

mytape.gradient(y,x)

In [122]:
print(mytape.gradient(y,x))

None


- 미분계산에 사용할 변수는 `tf.Variable`로 설정해야 한다

`-` 자동감시모드 & 수동감시모드

`-` 예시

`notename.watch(x):`를 사용하면 미분계산에 사용할 변수($x$)를 tf.constant()로 설정하였더라도 계산이 된다.

In [123]:
x=tf.constant([2.0])
a=x/2*3

with tf.GradientTape(persistent=True) as mytape:
    mytape.watch(x)
    y=a*x**2

mytape.gradient(y,x)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([12.], dtype=float32)>

- 계산이 되었음 !

``` python
tf.Variable(): 자동감시모드
tf.constant(): 감시 X
`notename.watch(감시할 변수)`사용: (감시할 변수에 대한) 수동감시모드
```

`-` 자동감시모드(기존)

In [125]:
x=tf.Variable([2.0])
a=x/2*3

with tf.GradientTape(persistent=True) as mytape:
    y=a*x**2

mytape.gradient(y,x)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([12.], dtype=float32)>

`-` 자동감시모드 off 
: `watch_accessed_variables=False` 사용

In [126]:
x=tf.Variable([2.0])
a=x/2*3

with tf.GradientTape(persistent=True,watch_accessed_variables=False) as mytape:
    y=a*x**2

mytape.gradient(y,x)

`-` 수동감시모드

In [134]:
x=tf.constant([2.0])
a=x/2*3

with tf.GradientTape(persistent=True) as mytape:
    mytape.watch(x) # 수동감시
    y=a*x**2

mytape.gradient(y,x)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([12.], dtype=float32)>

`-` 자동감시모드 -> 자동감시모드 off -> 수동감시 ON

In [132]:
x=tf.Variable([2.0])
a=x/2*3

with tf.GradientTape(persistent=True,watch_accessed_variables=False) as mytape:
    mytape.watch(x)
    y=a*x**2

mytape.gradient(y,x)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([12.], dtype=float32)>

- 가능!

- 헷갈리면 언제나 mytape.watch(변수)를 명시해도 괜찮음!
- 오류가 나는 것은 아니니!

#### 추가학습

`-` tf.GradientTape( )를 이용하여 $y=x^2$에서 $x=0$에서의 접선의 기울기를 구하라.

In [147]:
x=tf.constant([0.0])
with tf.GradientTape(persistent=True) as mytape:
    mytape.watch(x)
    y=x**2
    
mytape.gradient(y,x)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>