# DS 2. Tensorflow 기본 문법 - tf.constant

> "작성완료"

- toc:true
- branch: master
- badges: true
- comments: true
- [python, Data Science]

---
# Data Science
- lenture: Data Science_2-2, 3-1nd week of lectures.
- lenture date: 2022-03-14, 2022-03-16
- lecturer: Guebin choi
- study date: 2022-03-18, 2022-03-20
- author: Kione kim
---

## Tensorflow 사용법

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.config.experimental.list_physical_devices('GPU')

[]

- NO GPU

### tf.constant

#### 예비학습: 중첩리스트

In [3]:
[1,[2,3]]

[1, [2, 3]]

In [4]:
_[1][1]

3

In [5]:
lst = [[1,2],[3,4]]
lst

[[1, 2], [3, 4]]

In [6]:
lst[0][1]

2

In [7]:
lst[1][0]

3

``` python
1 2
3 4
```

In [8]:
print(lst[0][0]) # (1,1)
print(lst[0][1]) # (1,2)
print(lst[1][0]) # (2,1)
print(lst[1][1]) # (2,2)

1
2
3
4


- 이는 벡터일 뿐인데 매트릭스처럼 보임(매트릭스는 아님)

`-` 이를(매트릭스처럼 보이는 것을) 활용하여 행렬을 만들어보자

$4×2$

In [9]:
lst = [[1,2],[3,4],[5,6],[7,8]]
lst

[[1, 2], [3, 4], [5, 6], [7, 8]]

$4×1$

In [9]:
lst = [[1],[2],[3],[4]]
lst # 길이가 4인 column-vector처럼 보임

[[1], [2], [3], [4]]

$2×4$

In [10]:
lst = [[1,2,3,4],[5,6,7,8]]
lst

[[1, 2, 3, 4], [5, 6, 7, 8]]

$1×4$

In [11]:
lst = [[1,2,3,4]]
lst # 길이가 4인 row-vector처럼 보임

[[1, 2, 3, 4]]

`-` 3차원

In [10]:
lst = [[[1,2],[3,4]],[[5,6],[7,8]]] # 2×2×2 매트릭스처럼 보임
lst

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

In [11]:
# 차원 1
print(lst[0][0][0])
print(lst[0][0][1])
print(lst[0][1][0])
print(lst[0][1][1])

# 차원 2
print(lst[1][0][0])
print(lst[1][0][1])
print(lst[1][1][0])
print(lst[1][1][1])

1
2
3
4
5
6
7
8


#### 선언

`-` 스칼라

In [28]:
_scalar = tf.constant(1)
_scalar

<tf.Tensor: shape=(), dtype=int32, numpy=1>

`-` 벡터

In [23]:
[1,2,3] # 리스트

[1, 2, 3]

In [21]:
_vector = tf.constant([1,2,3]) # 리스트를 tf.constant()함수를 사용하여 벡터로
_vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [22]:
_vector[-1], _vector[-2]

(<tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

`-` 아래 두 코드는 다름. 두 번째 코드는 의도하지 않은 결과임

In [19]:
a=tf.constant([1,2,3,4])
a

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [20]:
a=tf.constant(1,2,3,4)
a

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 1., 1.])>

- tf.constant([ ]) `[ ]`를 사용해주어야 함 !

`-` 매트릭스

In [29]:
_mat = tf.constant([[1,2,3],[4,5,6]])
_mat

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

- 하나의 행렬로 묶을 때는 행렬처음과 끝에 `[ ]`로 받아주어야 한다.

In [30]:
_mat[0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [31]:
_mat[0][0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [32]:
_mat[0,0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

- _mat[0][0]를 _mat[0,0]와 같이 사용할 수 있다

`-` 첫번째 행을 뽑는 방법

`-` 방법1

In [33]:
_mat[0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

`-` 방법2

In [34]:
_mat[0,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

`-` 첫번째 열을 뽑는 방법

In [37]:
_mat[:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4])>

In [38]:
_mat[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 6])>

- 즉 행과 열을 모두 뽑을 수 있는 방법은 방법2이다. 확장성이 있음

In [39]:
type(_scalar)

tensorflow.python.framework.ops.EagerTensor

- EagerTensor임을 기억

In [40]:
type(_vector)

tensorflow.python.framework.ops.EagerTensor

#### tf.constant의 불편한점

```
1. dtype 모든 원소가 똑같아야함

2. 값을 바꿀 수 없음

3. dtype이 다르면 연산이 불가능
```

`2.` 값을 바꿀 수 없음

In [41]:
_mat[0,0] = 10

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

`3.` dtype이 다르면 연산 불가능

In [42]:
tf.constant([1,2])+ tf.constant([3,4])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6])>

In [43]:
tf.constant([1.1,2])+ tf.constant([3,4])

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2]

In [45]:
tf.constant([1.1,2])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.1, 2. ], dtype=float32)>

In [46]:
tf.constant([3,4])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4])>

- 뜯어보니, tf.constant([1.1,2])는 float형이고 tf.constant([3,4])는 int형이다. float과 int가 달라서 계산이 안 된 것,, ? OMG

`-` 다음과 같이 해야 한다

In [50]:
tf.constant([1.1,2])+tf.constant([3.,4.])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.1, 6. ], dtype=float32)>

In [51]:
tf.constant([1.1,2])+tf.constant([3,4.])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.1, 6. ], dtype=float32)>

In [52]:
tf.constant([1.1,2])+tf.constant([3.,4])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.1, 6. ], dtype=float32)>

- int형에 있는 하나의 원소에 `.`을 찍어주면 float형이 된다.

`-` 같은 float형이라도 불가능한 경우가 있음

In [54]:
tf.constant([1.1,2])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.1, 2. ], dtype=float32)>

In [55]:
tf.constant([3.0,4.0],dtype=tf.float64)

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([3., 4.])>

In [56]:
tf.constant([1.1,2])+tf.constant([3.0,4.0],dtype=tf.float64)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:AddV2]

- float32와 float64가 달라서 오류,,,? OMG2

#### tf.constant $\to$ 넘파이 

In [62]:
_vector = tf.constant([1,2,3,4])
_vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [63]:
np.array(_vector) # 방법1

array([1, 2, 3, 4])

In [64]:
_vector.numpy()

array([1, 2, 3, 4])

- Tensorflow 내에서 numpy를 쓸 수 있다

#### 연산

`-` 더하기 

In [65]:
a=tf.constant([1,2,3])
b=tf.constant([4,5,6])
a+b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9])>

In [66]:
tf.add(a,b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9])>

`-` 곱하기

In [67]:
a=tf.constant([[1,2],[3,4]])
b=tf.constant([[5,6],[7,8]])
a*b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]])>

In [44]:
tf.multiply(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]])>

- 각 원소끼리 곱

`-` 행렬곱

In [45]:
a=tf.constant([[1,2],[3,4]])
b=tf.constant([[1,0],[0,1]])
a@b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [46]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

`-` 역행렬

In [68]:
a=tf.constant([[1,0],[0,2]])
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 2]])>

In [69]:
tf.linalg.inv(a)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: double, float, half, complex64, complex128
	; NodeDef: {{node MatrixInverse}}; Op<name=MatrixInverse; signature=input:T -> output:T; attr=adjoint:bool,default=false; attr=T:type,allowed=[DT_DOUBLE, DT_FLOAT, DT_HALF, DT_COMPLEX64, DT_COMPLEX128]> [Op:MatrixInverse]

- 당연히 되어야하는데 오류가 남. 이는 a가 int이지만, 역행렬 값은 0.5(소수값)이 나오기 때문.. OMG3

- 따라서 다음과 같이 하면 가능..

In [70]:
a=tf.constant([[1.0,0],[0,2]])
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 2.]], dtype=float32)>

In [71]:
tf.linalg.inv(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1. , 0. ],
       [0. , 0.5]], dtype=float32)>

- a도 float형으로 했기 때문에 가능

In [73]:
a @ tf.linalg.inv(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>

`-` 행렬식, 대각합

In [74]:
a=tf.constant([[1.0,0],[0,2]])
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 2.]], dtype=float32)>

In [77]:
tf.linalg.det(a) 

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [78]:
tf.linalg.trace(a) 

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

`-` 집계함수

In [80]:
a=tf.constant([[1,2,3],[4,5,6]])
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [81]:
tf.reduce_sum(a)

<tf.Tensor: shape=(), dtype=int32, numpy=21>

In [82]:
tf.sum(a) # 잘못된 코드1

AttributeError: module 'tensorflow' has no attribute 'sum'

In [56]:
a.sum(a) # 잘못된 코드2

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'sum'

In [83]:
tf.reduce_max(a)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [84]:
tf.reduce_min(a)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [85]:
tf.reduce_mean(a)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

- 왜 평균이 3.5가 아닌 3이 나오지?

`-` 행렬곱 고급

In [89]:
_I=tf.constant([[1.0,0.0],[0.0,1.0]])
_I

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>

In [90]:
_x=tf.constant([11,22])
_x

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([11, 22])>

In [91]:
_I @ _x

InvalidArgumentError: cannot compute MatMul as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:MatMul]

- 오류가 남.    
- 이유: _x가 길이가 2인 열벡터도 아니고 길이가 2인 행벡터도 아니기 때문, _x는 그저 길이가 2인 벡터임

In [92]:
_x @ _I

InvalidArgumentError: cannot compute MatMul as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:MatMul]

- 이것 또한 마찬가지, 열벡터가 아니기 때문

`-` 다음과 같이 표현해주어야 함

`-` 열벡터 선언

In [99]:
_x=tf.constant([[11],[22]])
_x

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[11],
       [22]])>

`-` cf. 행벡터

In [100]:
_x=tf.constant([[11,22]])
_x

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[11, 22]])>

In [101]:
_I @ _x

InvalidArgumentError: cannot compute MatMul as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:MatMul]

- float형으로 선언해주지 않아서 난 오류

In [104]:
_x=tf.constant([[11.0],[22.0]])
_x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[11.],
       [22.]], dtype=float32)>

In [105]:
_I @ _x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[11.],
       [22.]], dtype=float32)>

`-` 행벡터 선언 `tf.constant([[ , ]])`

In [106]:
_x=tf.constant([[11.0,22.0]])
_x

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[11., 22.]], dtype=float32)>

In [108]:
_x @ _I

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[11., 22.]], dtype=float32)>

#### 형태변환

`-` 기본 

In [109]:
a=tf.constant([1,2,3,4])
a

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

- 이는 길이가 4인 벡터

In [110]:
tf.reshape(a,(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [111]:
tf.reshape(a,(4,1))

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4]])>

In [73]:
tf.reshape(a,(1,4))

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[1, 2, 3, 4]])>

`-` 응용 `-1`이용   
: `-1`은 자동 연산하여 값을 채워주는 기능

In [112]:
a=tf.constant([0,1,2,3,4,5,6,7,8,9,10,11])
a

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])>

In [113]:
tf.reshape(a,(4,3)) # 기본

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])>

In [76]:
tf.reshape(a,(4,-1)) # 응용

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])>

In [114]:
tf.reshape(a,(2,2,3)) # 기본

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])>

In [115]:
tf.reshape(a,(2,2,-1)) # 응용

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])>

In [116]:
tf.reshape(a,(3,2,2)) # 기본

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])>

In [117]:
tf.reshape(a,(3,2,-1))

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])>

In [118]:
tf.reshape(a,(2,-1))

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])>

- $2×6$ 행렬로 만들어줌, 즉, 3차원으로 만들고 싶을 땐 두 번째 값까지는 채워줘야 함

`-` reshape한 것을 다시 reshape 해줄 수 있음

`-` reshape한 것을 1차원으로 다시 만들어보자

In [119]:
b=tf.reshape(a,(2,2,-1))
b

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])>

In [120]:
tf.reshape(b,12) # 기본

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])>

In [121]:
tf.reshape(b,-1) # 응용

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])>

#### 선언고급

`-` 대각행렬선언

`-` 넘파이로 먼저 만들고 `tf.constant( )`를 사용하여 자료형 변환

In [85]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [86]:
tf.constant(np.diag([1,2,3]))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])>

`-` 1으로만 이루어진 텐서 만들기

In [87]:
tf.ones((3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [88]:
tf.ones([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [89]:
tf.reshape([1]*12,(3,4))

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])>

In [90]:
tf.reshape(tf.constant([1]*12),(3,4))

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])>

- 같은 결과

`-` 0으로만 이루어진 텐서 만들기

In [92]:
tf.zeros([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [93]:
tf.zeros((3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

`-` 리스트로 변환 후 텐서로 변환하지 않고 바로 텐서로 바꾸기   
: 즉,   
a $\to$ list $\to$ tensor - X   
a $\to$ tensor - O

In [99]:
range(12)

range(0, 12)

In [100]:
a=range(0,12)
a?

Type:        range
String form: range(0, 12)
Length:      12
Docstring:  
range(stop) -> range object
range(start, stop[, step]) -> range object

Return an object that produces a sequence of integers from start (inclusive)
to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
These are exactly the valid indices for a list of 4 elements.
When step is given, it specifies the increment (or decrement).


- range? 가 무엇인지는 모르겠지만, 일단 리스트로 바꿔보자.

In [98]:
list(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

- list 형태로 변환되었다.

`-` 동일한 논리로 range 가 무엇인지는 모르겠지만, tf.constant를 이용하여 텐서형태로 바꿔보자. (tf.constant가 텐서로 변환해주는 기능)

In [102]:
tf.constant(range(0,12))

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])>

In [104]:
tf.constant(range(1,12)) # 1부터 시작

<tf.Tensor: shape=(11,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])>

In [105]:
tf.constant(range(2,6))

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5])>

In [108]:
tf.constant(range(2,21,2)) # 2칸씩 점프

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])>

In [111]:
tf.constant(range(2,21,3)) # 3칸씩 점프

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([ 2,  5,  8, 11, 14, 17, 20])>

`-` 등간격 수열 만들기

In [114]:
tf.linspace(0,1,14) # 0 ~ 1 까지 길이가 14인 수열 만들기

<tf.Tensor: shape=(14,), dtype=float64, numpy=
array([0.        , 0.07692308, 0.15384615, 0.23076923, 0.30769231,
       0.38461538, 0.46153846, 0.53846154, 0.61538462, 0.69230769,
       0.76923077, 0.84615385, 0.92307692, 1.        ])>

In [116]:
tf.linspace(-1,20,14) # -1 ~ 20 까지 길이가 14인 수열

<tf.Tensor: shape=(14,), dtype=float64, numpy=
array([-1.        ,  0.61538462,  2.23076923,  3.84615385,  5.46153846,
        7.07692308,  8.69230769, 10.30769231, 11.92307692, 13.53846154,
       15.15384615, 16.76923077, 18.38461538, 20.        ])>

In [119]:
tf.linspace([0,-1],[14,20],14) # 첫 열: 0~14까지, 두 번째 열: -1~20까지 길이가 14인 수열

<tf.Tensor: shape=(14, 2), dtype=float64, numpy=
array([[ 0.        , -1.        ],
       [ 1.07692308,  0.61538462],
       [ 2.15384615,  2.23076923],
       [ 3.23076923,  3.84615385],
       [ 4.30769231,  5.46153846],
       [ 5.38461538,  7.07692308],
       [ 6.46153846,  8.69230769],
       [ 7.53846154, 10.30769231],
       [ 8.61538462, 11.92307692],
       [ 9.69230769, 13.53846154],
       [10.76923077, 15.15384615],
       [11.84615385, 16.76923077],
       [12.92307692, 18.38461538],
       [14.        , 20.        ]])>

`-` $14×2$가 아닌 $2×14$ 행렬은?

: `axis=1`사용

In [123]:
tf.linspace([0,-1],[1,20],14,axis=1)

<tf.Tensor: shape=(2, 14), dtype=float64, numpy=
array([[ 0.        ,  0.07692308,  0.15384615,  0.23076923,  0.30769231,
         0.38461538,  0.46153846,  0.53846154,  0.61538462,  0.69230769,
         0.76923077,  0.84615385,  0.92307692,  1.        ],
       [-1.        ,  0.61538462,  2.23076923,  3.84615385,  5.46153846,
         7.07692308,  8.69230769, 10.30769231, 11.92307692, 13.53846154,
        15.15384615, 16.76923077, 18.38461538, 20.        ]])>

In [124]:
tf.linspace([0,-1],[1,20],14,axis=0)

<tf.Tensor: shape=(14, 2), dtype=float64, numpy=
array([[ 0.        , -1.        ],
       [ 0.07692308,  0.61538462],
       [ 0.15384615,  2.23076923],
       [ 0.23076923,  3.84615385],
       [ 0.30769231,  5.46153846],
       [ 0.38461538,  7.07692308],
       [ 0.46153846,  8.69230769],
       [ 0.53846154, 10.30769231],
       [ 0.61538462, 11.92307692],
       [ 0.69230769, 13.53846154],
       [ 0.76923077, 15.15384615],
       [ 0.84615385, 16.76923077],
       [ 0.92307692, 18.38461538],
       [ 1.        , 20.        ]])>

`-` 랜덤

In [130]:
tf.random.normal([10])

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-2.031805  ,  0.0878811 , -0.08389507, -0.4712213 ,  1.7228402 ,
        1.5234696 , -0.45930204,  0.27446908,  0.6777201 ,  1.2311221 ],
      dtype=float32)>

In [131]:
tf.random.normal(10)

InvalidArgumentError: shape must be a vector of {int32,int64}, got shape [] [Op:RandomStandardNormal]

- 위와 같이 하면 오류가 남

In [128]:
tf.random.normal([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.67909116,  1.6647867 , -1.1921434 ],
       [-0.41828915, -1.007226  , -0.37517777],
       [-0.35723418, -0.90447557, -0.21201086]], dtype=float32)>

In [132]:
tf.random.uniform([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.49846053, 0.53244936, 0.37250876],
       [0.5088717 , 0.01882815, 0.50129974],
       [0.8890096 , 0.7716527 , 0.68743026]], dtype=float32)>

`-` numpy를 이용한 자료형 변환

In [135]:
a=np.random.randn(10)
a

array([ 1.42470939, -0.43431904,  0.35631914, -0.83401698,  0.98403914,
        0.03123622,  0.3625249 ,  0.45672775,  0.51236327,  0.74739683])

In [138]:
list(a) # 일단 리스트로 변환해 봄

[1.4247093944590954,
 -0.4343190394693054,
 0.35631913687969213,
 -0.8340169822900257,
 0.9840391372400604,
 0.031236220641082953,
 0.36252489894658657,
 0.4567277510989872,
 0.5123632705088501,
 0.7473968310235103]

In [139]:
tf.constant(a)

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([ 1.42470939, -0.43431904,  0.35631914, -0.83401698,  0.98403914,
        0.03123622,  0.3625249 ,  0.45672775,  0.51236327,  0.74739683])>

`-` tf.random이 numpy에 있는 모든 기능을 구현하는 것은 아님.

In [140]:
np.random.randn(10)

array([-0.37923556,  1.89366845, -0.60768019,  0.89680048, -0.11687065,
       -0.67507322,  3.45690649,  0.13774121,  0.5305251 , -0.37030568])

In [143]:
tf.random.randn([10])

AttributeError: module 'tensorflow._api.v2.random' has no attribute 'randn'

#### tf.concat

``` python
tf.concat 사용법: 축 지정이 매우 헷갈리기 때문에 외우는 게 필요함
python은 0부터 시작하기 때문에 첫 번째 축이 0을 의미, 두 번째 축이 1을 의미, 세 번째 축이 2를 의미한다.
(2차원에선) 함수 축을 그릴 때 가로를 그린 후 세로를 그리기 때문에 첫 번째 축이 가로, 두 번째 축이 세로를 의미한다. 
(2차원에선) 따라서 axis=0은 가로로 쌓는다는 것(아래로 계속해서)을 의미하고 axis=1은 세로로 쌓는다는 것(옆으로 계속해서)을 의미한다.
3차원부터는 앞서 정리한 것처럼 첫 번째 축-0, 두 번째 축-1, 세 번째 축-2 으로 외우는 것이 좋다.
```

`-` $2×1$ 벡터와 $2×1$ 벡터를 concat해서 $2×2$ 벡터로 만든다

In [149]:
a=tf.constant([[1],[2]])
b=tf.constant([[3],[4]])

In [150]:
a,b

(<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[1],
        [2]])>,
 <tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[3],
        [4]])>)

In [151]:
tf.concat([a,b])

TypeError: Missing required positional argument

`-` concat을 사용할 때는 축을 반드시 지정해주어야 한다. 그렇지 않으면 위와 같이 오류가 뜬다.

In [153]:
tf.concat([a,b],axis=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]])>

`-` $2×1$ 벡터와 $2×1$ 벡터를 concat해서 $4×1$ 벡터로 만든다

In [154]:
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4]])>

`-` $1×2$ 벡터와 $1×2$ 벡터를 concat해서 $2×2$ 벡터로 만든다

In [156]:
a=tf.constant([1,2])
b=tf.constant([3,4])
a,b

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4])>)

In [158]:
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

- 의도하지 않은 결과가 나타나는 이유?    
: 전체 축에 대한 `[ ]`를 입력해주지 않았기 때문.......

In [162]:
a=tf.constant([[1,2]])
b=tf.constant([[3,4]])
a,b

(<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1, 2]])>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[3, 4]])>)

In [163]:
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

`-` $1×2$ 벡터와 $1×2$ 벡터를 concat해서 $1×4$ 벡터로 만든다

In [164]:
tf.concat([a,b],axis=1)

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[1, 2, 3, 4]])>

- axis=0은 아래로 쌓이고 axis=1은 옆으로 쌓인다고 기억하자.

`-` 3차원으로 확장해보자   
: 첫 번째 축이 무엇인지 파악하는 것이 중요함 ! 다음 예제에서 첫 번째 축은 $2×3$행렬이 두 개 있는 3차원 축을 의미함

In [177]:
a=tf.reshape(tf.constant(range(12)),(2,2,3))
b=-a
a,b

(<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[ 0,  1,  2],
         [ 3,  4,  5]],
 
        [[ 6,  7,  8],
         [ 9, 10, 11]]])>,
 <tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[  0,  -1,  -2],
         [ -3,  -4,  -5]],
 
        [[ -6,  -7,  -8],
         [ -9, -10, -11]]])>)

`-` $2×2×3$ 벡터와 $2×2×3$ 벡터를 concat해서 $4×2×3$ 벡터로 만든다

In [180]:
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[  0,   1,   2],
        [  3,   4,   5]],

       [[  6,   7,   8],
        [  9,  10,  11]],

       [[  0,  -1,  -2],
        [ -3,  -4,  -5]],

       [[ -6,  -7,  -8],
        [ -9, -10, -11]]])>

- 합치고자 하는 것이 첫 번째 축이기 때문에 axis=0을 이용한다

`-` $2×2×3$ 벡터와 $2×2×3$ 벡터를 concat해서 $2×4×3$ 벡터로 만든다

In [182]:
tf.concat([a,b],axis=1)

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[  0,   1,   2],
        [  3,   4,   5],
        [  0,  -1,  -2],
        [ -3,  -4,  -5]],

       [[  6,   7,   8],
        [  9,  10,  11],
        [ -6,  -7,  -8],
        [ -9, -10, -11]]])>

- 합치고자 하는 것이 두 번째 축이기 때문에 axis=1을 이용한다

`-` $2×2×3$ 벡터와 $2×2×3$ 벡터를 concat해서 $2×2×6$ 벡터로 만든다

In [183]:
tf.concat([a,b],axis=2)

<tf.Tensor: shape=(2, 2, 6), dtype=int32, numpy=
array([[[  0,   1,   2,   0,  -1,  -2],
        [  3,   4,   5,  -3,  -4,  -5]],

       [[  6,   7,   8,  -6,  -7,  -8],
        [  9,  10,  11,  -9, -10, -11]]])>

- 합치고자 하는 것이 세 번째 축이기 때문에 axis=2를 이용한다.

`-` 다른 가능한 방법

In [184]:
tf.concat([a,b],axis=-1)

<tf.Tensor: shape=(2, 2, 6), dtype=int32, numpy=
array([[[  0,   1,   2,   0,  -1,  -2],
        [  3,   4,   5,  -3,  -4,  -5]],

       [[  6,   7,   8,  -6,  -7,  -8],
        [  9,  10,  11,  -9, -10, -11]]])>

- 이는 `axis=2`와 같다. 이는 -1이 뒤에서 첫번째 숫자를 의미하고 2가 뒤에서 첫번째 숫자(마지막 숫자)이기 때문이다

In [186]:
tf.concat([a,b],axis=1)

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[  0,   1,   2],
        [  3,   4,   5],
        [  0,  -1,  -2],
        [ -3,  -4,  -5]],

       [[  6,   7,   8],
        [  9,  10,  11],
        [ -6,  -7,  -8],
        [ -9, -10, -11]]])>

In [187]:
tf.concat([a,b],axis=-2)

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[  0,   1,   2],
        [  3,   4,   5],
        [  0,  -1,  -2],
        [ -3,  -4,  -5]],

       [[  6,   7,   8],
        [  9,  10,  11],
        [ -6,  -7,  -8],
        [ -9, -10, -11]]])>

- 마찬가지로 위 두 코드는 같은 결과를 나타낸다.

`-` $(4,)$와 $(4,)$ concat $(8,)$

In [188]:
a=tf.constant([1,2,3,4])
b=-a
a,b

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([-1, -2, -3, -4])>)

In [190]:
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 1,  2,  3,  4, -1, -2, -3, -4])>

In [191]:
tf.concat([a,b],axis=1)

InvalidArgumentError: ConcatOp : Expected concatenating dimensions in the range [-1, 1), but got 1 [Op:ConcatV2] name: concat

- axis=0 으로 하면 $2×4$벡터가 만들어져야 하는 거 아닌가?   
- 즉, axis=1로 해야 길이가 $8$인 벡터가 만들어지는 거 아닌가?   
- 그런데 심지어 axis=1은 오류까지 뜬다?!

- 이유: $(4,),(4,),(8,)$은 길이가 각각 4,4,8인 **튜플**(1차원)이기에 애초에 축이 1개만 존재했기 때문이다. 즉 축이 2개가 존재하지 않기에 axis=1은 오류가 나고 축이 하나만 존재(1차원 형태)하기에 axis=0만 가능하다. 따라서 $2×4$ 또는 $4×2$(2차원 형태)는 애초에 불가능하다.

- tf.concat은 dimension(차원)을 변환시킬 수 없다.

즉, one dimension $\to$ 결과 one,    
two dimension $\to$ 결과 two,   
three dimension $\to$ 결과 three

dimension(차원)을 변환시키려면 다음과 같이 tf.stack을 사용해야 한다.

#### tf.stack

`-` $(4)$ 벡터와 $(4)$ 벡터를 concat해서 $(4,2)$ 벡터로 만든다
- $(4, )$ stack $(4, )$ $\to$ $(4,2)$ : 두 번째 축을 비어있다고 인식

In [194]:
a=tf.stack([1,2,3,4])
b=-a
a,b

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([-1, -2, -3, -4])>)

In [196]:
tf.stack?

Signature: tf.stack(values, axis=0, name='stack')
Docstring:
Stacks a list of rank-`R` tensors into one rank-`(R+1)` tensor.

See also `tf.concat`, `tf.tile`, `tf.repeat`.

Packs the list of tensors in `values` into a tensor with rank one higher than
each tensor in `values`, by packing them along the `axis` dimension.
Given a list of length `N` of tensors of shape `(A, B, C)`;

if `axis == 0` then the `output` tensor will have the shape `(N, A, B, C)`.
if `axis == 1` then the `output` tensor will have the shape `(A, N, B, C)`.
Etc.

For example:

>>> x = tf.constant([1, 4])
>>> y = tf.constant([2, 5])
>>> z = tf.constant([3, 6])
>>> tf.stack([x, y, z])
<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>
>>> tf.stack([x, y, z], axis=1)
<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

This is the opposite of unstack.  The numpy equivalent is `np.stack`

>>> np.array_equal(np.stack([x, y

- tf.stack()은 default가 `axis=0`이다

In [195]:
tf.stack([a,b])

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [-1, -2, -3, -4]])>

In [199]:
tf.stack([a,b],axis=0)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [-1, -2, -3, -4]])>

- 따라서 위 두 코드가 같다

In [200]:
tf.stack([a,b],axis=1)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 1, -1],
       [ 2, -2],
       [ 3, -3],
       [ 4, -4]])>

`-` $(4)$ 벡터와 $(4)$ 벡터를 concat해서 $(4,2)$ 벡터로 만든다
- $(4, )$ stack $(4, )$ $\to$ $(4,2)$ : 두 번째 축을 비어있다고 인식

In [201]:
tf.stack([a,b],axis=0)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [-1, -2, -3, -4]])>

`-` (2,3,4,5) stack (2,3,4,5) $\to$ (2,2,3,4,5)   
: 첫 번째 축이 비어있다고 인식

In [205]:
a=tf.reshape(tf.constant(range(2*3*4*5)),(2,3,4,5))
b=-a
a,b

(<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
 array([[[[  0,   1,   2,   3,   4],
          [  5,   6,   7,   8,   9],
          [ 10,  11,  12,  13,  14],
          [ 15,  16,  17,  18,  19]],
 
         [[ 20,  21,  22,  23,  24],
          [ 25,  26,  27,  28,  29],
          [ 30,  31,  32,  33,  34],
          [ 35,  36,  37,  38,  39]],
 
         [[ 40,  41,  42,  43,  44],
          [ 45,  46,  47,  48,  49],
          [ 50,  51,  52,  53,  54],
          [ 55,  56,  57,  58,  59]]],
 
 
        [[[ 60,  61,  62,  63,  64],
          [ 65,  66,  67,  68,  69],
          [ 70,  71,  72,  73,  74],
          [ 75,  76,  77,  78,  79]],
 
         [[ 80,  81,  82,  83,  84],
          [ 85,  86,  87,  88,  89],
          [ 90,  91,  92,  93,  94],
          [ 95,  96,  97,  98,  99]],
 
         [[100, 101, 102, 103, 104],
          [105, 106, 107, 108, 109],
          [110, 111, 112, 113, 114],
          [115, 116, 117, 118, 119]]]])>,
 <tf.Tensor: shape=(2, 3, 4, 5), dty

In [207]:
tf.stack([a,b],axis=0)

<tf.Tensor: shape=(2, 2, 3, 4, 5), dtype=int32, numpy=
array([[[[[   0,    1,    2,    3,    4],
          [   5,    6,    7,    8,    9],
          [  10,   11,   12,   13,   14],
          [  15,   16,   17,   18,   19]],

         [[  20,   21,   22,   23,   24],
          [  25,   26,   27,   28,   29],
          [  30,   31,   32,   33,   34],
          [  35,   36,   37,   38,   39]],

         [[  40,   41,   42,   43,   44],
          [  45,   46,   47,   48,   49],
          [  50,   51,   52,   53,   54],
          [  55,   56,   57,   58,   59]]],


        [[[  60,   61,   62,   63,   64],
          [  65,   66,   67,   68,   69],
          [  70,   71,   72,   73,   74],
          [  75,   76,   77,   78,   79]],

         [[  80,   81,   82,   83,   84],
          [  85,   86,   87,   88,   89],
          [  90,   91,   92,   93,   94],
          [  95,   96,   97,   98,   99]],

         [[ 100,  101,  102,  103,  104],
          [ 105,  106,  107,  108,  109],
         

`-` (2,3,4,5) stack (2,3,4,5)   
- 두 번째 축이 비어있다고 인식
- (2,?,3,4,5) stack (2,?,3,4,5) $\to$ (2,2,3,4,5)

In [208]:
tf.stack([a,b],axis=1)

<tf.Tensor: shape=(2, 2, 3, 4, 5), dtype=int32, numpy=
array([[[[[   0,    1,    2,    3,    4],
          [   5,    6,    7,    8,    9],
          [  10,   11,   12,   13,   14],
          [  15,   16,   17,   18,   19]],

         [[  20,   21,   22,   23,   24],
          [  25,   26,   27,   28,   29],
          [  30,   31,   32,   33,   34],
          [  35,   36,   37,   38,   39]],

         [[  40,   41,   42,   43,   44],
          [  45,   46,   47,   48,   49],
          [  50,   51,   52,   53,   54],
          [  55,   56,   57,   58,   59]]],


        [[[   0,   -1,   -2,   -3,   -4],
          [  -5,   -6,   -7,   -8,   -9],
          [ -10,  -11,  -12,  -13,  -14],
          [ -15,  -16,  -17,  -18,  -19]],

         [[ -20,  -21,  -22,  -23,  -24],
          [ -25,  -26,  -27,  -28,  -29],
          [ -30,  -31,  -32,  -33,  -34],
          [ -35,  -36,  -37,  -38,  -39]],

         [[ -40,  -41,  -42,  -43,  -44],
          [ -45,  -46,  -47,  -48,  -49],
         

`-` (2,3,4,5) stack (2,3,4,5)
- 마지막 축이 비어있다고 인식   
- (2,3,4,5,?) stack (2,3,4,5,?) $\to$ (2,3,4,5,2)

In [209]:
tf.stack([a,b],axis=-1)

<tf.Tensor: shape=(2, 3, 4, 5, 2), dtype=int32, numpy=
array([[[[[   0,    0],
          [   1,   -1],
          [   2,   -2],
          [   3,   -3],
          [   4,   -4]],

         [[   5,   -5],
          [   6,   -6],
          [   7,   -7],
          [   8,   -8],
          [   9,   -9]],

         [[  10,  -10],
          [  11,  -11],
          [  12,  -12],
          [  13,  -13],
          [  14,  -14]],

         [[  15,  -15],
          [  16,  -16],
          [  17,  -17],
          [  18,  -18],
          [  19,  -19]]],


        [[[  20,  -20],
          [  21,  -21],
          [  22,  -22],
          [  23,  -23],
          [  24,  -24]],

         [[  25,  -25],
          [  26,  -26],
          [  27,  -27],
          [  28,  -28],
          [  29,  -29]],

         [[  30,  -30],
          [  31,  -31],
          [  32,  -32],
          [  33,  -33],
          [  34,  -34]],

         [[  35,  -35],
          [  36,  -36],
          [  37,  -37],
          [  38, 